--[[
[!] GUI Generated by Gui to Lua v3.0
[!] Made by awesomedude939
]]

-- Pre-Functions

function buttonfy(btn,lb)
	btn.MouseEnter:Connect(function()
		lb.BackgroundColor3 = Color3.fromRGB(228,238,254)
	end)
	btn.MouseLeave:Connect(function()
		lb.BackgroundColor3 = Color3.fromRGB(255,255,255)
	end)
end

function textboxify(btn,lb)
	btn.Focused:Connect(function()
		lb.BackgroundColor3 = Color3.fromRGB(0,162,255)
	end)
	btn.FocusLost:Connect(function()
		lb.BackgroundColor3 = Color3.fromRGB(182, 182, 182)
	end)
end

-- Variables

local https = game:GetService("HttpService")

local ratemyavatar = Instance.new("ScreenGui")
local bar = Instance.new("Frame")
local main = Instance.new("Frame")
local saveTab = Instance.new("Frame")
local savebtn = Instance.new("TextButton")
local UICorner = Instance.new("UICorner")
local savebtndec = Instance.new("Frame")
local UICorner_2 = Instance.new("UICorner")
local savebtnlb = Instance.new("TextLabel")
local UICorner_3 = Instance.new("UICorner")
local namelb = Instance.new("TextLabel")
local name = Instance.new("TextBox")
local UICorner_4 = Instance.new("UICorner")
local UICorner_5 = Instance.new("UICorner")
local descriptionlb = Instance.new("TextLabel")
local description = Instance.new("TextBox")
local UICorner_6 = Instance.new("UICorner")
local UICorner_7 = Instance.new("UICorner")
local openTab = Instance.new("Frame")
local openbtn = Instance.new("TextButton")
local UICorner_8 = Instance.new("UICorner")
local openbtndec = Instance.new("Frame")
local UICorner_9 = Instance.new("UICorner")
local openbtnlb = Instance.new("TextLabel")
local UICorner_10 = Instance.new("UICorner")
local namelbo = Instance.new("TextLabel")
local nameo = Instance.new("TextBox")
local UICorner_11 = Instance.new("UICorner")
local UICorner_12 = Instance.new("UICorner")
local descriptionlbo = Instance.new("TextLabel")
local descriptiono = Instance.new("TextBox")
local UICorner_13 = Instance.new("UICorner")
local UICorner_14 = Instance.new("UICorner")
local scrolldec = Instance.new("Frame")
local UICorner_15 = Instance.new("UICorner")
local ScrollingFrame = Instance.new("ScrollingFrame")
local UIListLayout = Instance.new("UIListLayout")
local UICorner_16 = Instance.new("UICorner")
local filedefault = Instance.new("TextButton")
local filename = Instance.new("TextLabel")
local fileicon = Instance.new("ImageLabel")
local df = Instance.new("Frame")
local dflabel = Instance.new("TextLabel")
local mainlist = Instance.new("Frame")
local svlistbtn = Instance.new("TextButton")
local svlist = Instance.new("TextLabel")
local svlistlb = Instance.new("TextLabel")
local svasel = Instance.new("Frame")
local UIListLayout_2 = Instance.new("UIListLayout")
local oplistbtn = Instance.new("TextButton")
local oplist = Instance.new("TextLabel")
local oplistlb = Instance.new("TextLabel")
local opasel = Instance.new("Frame")
local edlistbtn = Instance.new("TextButton")
local edlist = Instance.new("TextLabel")
local edlistlb = Instance.new("TextLabel")
local edasel = Instance.new("Frame")
local menubtn = Instance.new("TextButton")
local menulist = Instance.new("TextLabel")
local menulistlb = Instance.new("TextLabel")
local menuasel = Instance.new("Frame")
local menubtn = Instance.new("TextButton")
local menulist = Instance.new("TextLabel")
local menulistlb = Instance.new("TextLabel")
local editTab = Instance.new("Frame")
local loopedcheck = Instance.new("TextButton")
local loopedchecklb = Instance.new("Frame")
local checklooped = Instance.new("ImageLabel")
local Frame = Instance.new("Frame")
local UIListLayout_3 = Instance.new("UIListLayout")
local deletebtn = Instance.new("TextButton")
local UICorner_17 = Instance.new("UICorner")
local deletebtndec = Instance.new("Frame")
local UICorner_18 = Instance.new("UICorner")
local deletebtnlb = Instance.new("TextLabel")
local UICorner_19 = Instance.new("UICorner")
local newfrbtn = Instance.new("TextButton")
local UICorner_20 = Instance.new("UICorner")
local newfrbtndec = Instance.new("Frame")
local UICorner_21 = Instance.new("UICorner")
local newfrbtnlb = Instance.new("TextLabel")
local UICorner_22 = Instance.new("UICorner")
local updatebtn = Instance.new("TextButton")
local UICorner_23 = Instance.new("UICorner")
local updatebtndec = Instance.new("Frame")
local UICorner_24 = Instance.new("UICorner")
local updatebtnlb = Instance.new("TextLabel")
local UICorner_25 = Instance.new("UICorner")
local textureidlb = Instance.new("TextLabel")
local textureidtb = Instance.new("TextBox")
local UICorner_26 = Instance.new("UICorner")
local UICorner_27 = Instance.new("UICorner")
local textlb = Instance.new("TextLabel")
local texttb = Instance.new("TextBox")
local UICorner_28 = Instance.new("UICorner")
local UICorner_29 = Instance.new("UICorner")
local editframe = Instance.new("Frame")
local UICorner_30 = Instance.new("UICorner")
local editscroll = Instance.new("ScrollingFrame")
local UIGridLayout = Instance.new("UIGridLayout")
local def = Instance.new("Frame")
local placeholderimg = Instance.new("ImageButton")
local placeholdertxt = Instance.new("TextLabel")
local placeholderlayout = Instance.new("TextLabel")
local placeholdertime = Instance.new("TextLabel")
local waitlb = Instance.new("TextLabel")
local waittb = Instance.new("TextBox")
local UICorner_31 = Instance.new("UICorner")
local UICorner_32 = Instance.new("UICorner")
local pausebtn = Instance.new("TextButton")
local pauselb = Instance.new("ImageLabel")
local menuTab = Instance.new("Frame")
local checkupdbtn = Instance.new("TextButton")
local UICorner_33 = Instance.new("UICorner")
local checkupdbtndec = Instance.new("Frame")
local UICorner_34 = Instance.new("UICorner")
local checkupdbtnlb = Instance.new("TextLabel")
local UICorner_35 = Instance.new("UICorner")
local credits = Instance.new("TextLabel")
local versiondetected = Instance.new("TextLabel")
local warnings = Instance.new("TextLabel")
local closebtn = Instance.new("TextButton")
local closelb = Instance.new("TextLabel")
local closeimg = Instance.new("ImageButton")
local title = Instance.new("TextLabel")
local realimg = Instance.new("TextLabel")
local rootbtn = Instance.new("TextButton")
local rootcorner1 = Instance.new("UICorner")
local rootbtndec = Instance.new("Frame")
local rootcorner2 = Instance.new("UICorner")
local rootbtnlb = Instance.new("TextLabel")
local rootcorner3 = Instance.new("UICorner")

-- Functions

function formatfile(name,description,looping)
	if #description <= 0 then 
		description = "No description."
	end

	local tablesa = {
		["config"] = {
			["name"] = name,
			["description"] = description,
			["looping"] = looping,
			["file"] = ".RMAS"
		},
		["anim"] = {

		}
	}
	for i,v in pairs(editscroll:GetChildren()) do 
		if not v:IsA("UIGridLayout") and v.Name ~= "def" then 
			tablesa.anim[tostring(v.placeholderlayout.Text)] = {}
			tablesa.anim[tostring(v.placeholderlayout.Text)].index_ = tonumber(v.placeholderlayout)
			tablesa.anim[tostring(v.placeholderlayout.Text)].id = v.realimg.Text
			tablesa.anim[tostring(v.placeholderlayout.Text)].text = v.placeholdertxt.Text
			tablesa.anim[tostring(v.placeholderlayout.Text)].sleep = tonumber(v.placeholdertime.Text) or 0
		end
	end
	return tablesa
end

-- Gui

ratemyavatar.Name = "ratemyavatar"
ratemyavatar.Parent = game.Players.LocalPlayer:WaitForChild("PlayerGui")
ratemyavatar.ZIndexBehavior = Enum.ZIndexBehavior.Sibling

bar.Name = "bar"
bar.Parent = ratemyavatar
bar.BackgroundColor3 = Color3.fromRGB(227, 227, 227)
bar.BorderSizePixel = 0
bar.Position = UDim2.new(0.6677531, 0, 0.318584055, 0)
bar.Size = UDim2.new(0, 440, 0, 23)
bar.Active = true
bar.Draggable = true

main.Name = "main"
main.Parent = bar
main.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
main.BorderSizePixel = 0
main.Position = UDim2.new(0, 0, 0.978999972, 0)
main.Size = UDim2.new(0, 440, 0, 187)

saveTab.Name = "saveTab"
saveTab.Parent = main
saveTab.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
saveTab.BackgroundTransparency = 1.000
saveTab.Size = UDim2.new(0, 440, 0, 187)
saveTab.Visible = false

savebtn.Name = "savebtn"
savebtn.Parent = saveTab
savebtn.BackgroundColor3 = Color3.fromRGB(0, 0, 0)
savebtn.BorderSizePixel = 5
savebtn.Position = UDim2.new(0.647727251, 0, 0.737967908, 0)
savebtn.Size = UDim2.new(0, 136, 0, 30)
savebtn.Font = Enum.Font.SourceSans
savebtn.Text = ""
savebtn.TextColor3 = Color3.fromRGB(0, 0, 0)
savebtn.TextSize = 14.000
buttonfy(savebtn,savebtnlb)
savebtn.MouseButton1Click:Connect(function()
	local looped = false
	if checklooped.Image == "http://www.roblox.com/asset/?id=9398101174" then 
		looped = true
	end
	if #name.Text <= 0 then
		name.Text = "unnamed"
	end
	writefile(name.Text..".rmas", https:JSONEncode(formatfile(name.Text,description.Text,looped)))
end)

UICorner.CornerRadius = UDim.new(0, 4)
UICorner.Parent = savebtn

savebtndec.Name = "savebtndec"
savebtndec.Parent = savebtn
savebtndec.BackgroundColor3 = Color3.fromRGB(182, 182, 182)
savebtndec.Size = UDim2.new(0, 136, 0, 30)

UICorner_2.CornerRadius = UDim.new(0, 4)
UICorner_2.Parent = savebtndec

savebtnlb.Name = "savebtnlb"
savebtnlb.Parent = savebtndec
savebtnlb.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
savebtnlb.Position = UDim2.new(0, 1, 0, 1)
savebtnlb.Selectable = true
savebtnlb.Size = UDim2.new(0, 134, 0, 28)
savebtnlb.Font = Enum.Font.SourceSans
savebtnlb.Text = "Save"
savebtnlb.TextColor3 = Color3.fromRGB(0, 0, 0)
savebtnlb.TextSize = 14.000

UICorner_3.CornerRadius = UDim.new(0, 4)
UICorner_3.Parent = savebtnlb

namelb.Name = "namelb"
namelb.Parent = saveTab
namelb.BackgroundColor3 = Color3.fromRGB(182, 182, 182)
namelb.Position = UDim2.new(0.345454544, 0, 0.053475935, 0)
namelb.Size = UDim2.new(0, 138, 0, 26)
namelb.Font = Enum.Font.SourceSans
namelb.TextColor3 = Color3.fromRGB(0, 0, 0)
namelb.TextSize = 14.000

name.Name = "name"
name.Parent = namelb
name.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
name.BorderColor3 = Color3.fromRGB(200, 200, 200)
name.Position = UDim2.new(0, 1, 0, 1)
name.Size = UDim2.new(0, 136, 0, 24)
name.ClearTextOnFocus = false
name.Font = Enum.Font.SourceSans
name.PlaceholderColor3 = Color3.fromRGB(68, 68, 68)
name.PlaceholderText = "Name"
name.Text = ""
name.TextColor3 = Color3.fromRGB(0, 0, 0)
name.TextSize = 14.000
name.TextWrapped = true
textboxify(name,namelb)

UICorner_4.CornerRadius = UDim.new(0, 4)
UICorner_4.Parent = name

UICorner_5.CornerRadius = UDim.new(0, 4)
UICorner_5.Parent = namelb

descriptionlb.Name = "descriptionlb"
descriptionlb.Parent = saveTab
descriptionlb.BackgroundColor3 = Color3.fromRGB(182, 182, 182)
descriptionlb.Position = UDim2.new(0.343181819, 0, 0.294117659, 0)
descriptionlb.Size = UDim2.new(0, 138, 0, 62)
descriptionlb.Font = Enum.Font.SourceSans
descriptionlb.TextColor3 = Color3.fromRGB(0, 0, 0)
descriptionlb.TextSize = 14.000

description.Name = "description"
description.Parent = descriptionlb
description.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
description.BorderColor3 = Color3.fromRGB(200, 200, 200)
description.Position = UDim2.new(0, 1, 0, 1)
description.Size = UDim2.new(0, 136, 0, 60)
description.ClearTextOnFocus = false
description.Font = Enum.Font.SourceSans
description.PlaceholderColor3 = Color3.fromRGB(68, 68, 68)
description.PlaceholderText = "Description"
description.Text = ""
description.TextColor3 = Color3.fromRGB(0, 0, 0)
description.TextSize = 14.000
description.TextWrapped = true
textboxify(description,descriptionlb)


UICorner_6.CornerRadius = UDim.new(0, 4)
UICorner_6.Parent = description

UICorner_7.CornerRadius = UDim.new(0, 4)
UICorner_7.Parent = descriptionlb

def.Name = "def"
def.Parent = editscroll
def.BackgroundColor3 = Color3.fromRGB(207, 207, 207)
def.BorderColor3 = Color3.fromRGB(113, 113, 113)
def.BorderSizePixel = 2
def.Position = UDim2.new(0.581296504, 0, 0.481415927, 0)
def.Size = UDim2.new(0, 97, 0, 48)
def.Visible = false

placeholderimg.Name = "placeholderimg"
placeholderimg.Parent = def
placeholderimg.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
placeholderimg.BackgroundTransparency = 1.000
placeholderimg.Size = UDim2.new(0, 97, 0, 48)
placeholderimg.Image = "rbxasset://textures/ui/GuiImagePlaceholder.png"

placeholdertxt.Name = "placeholdertxt"
placeholdertxt.Parent = def
placeholdertxt.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
placeholdertxt.BackgroundTransparency = 1.000
placeholdertxt.BorderSizePixel = 0
placeholdertxt.Position = UDim2.new(0, 0, 0.020833334, 0)
placeholdertxt.Size = UDim2.new(0, 53, 0, 47)
placeholdertxt.Font = Enum.Font.SourceSans
placeholdertxt.Text = "text"
placeholdertxt.TextColor3 = Color3.fromRGB(255, 255, 255)
placeholdertxt.TextScaled = true
placeholdertxt.TextSize = 14.000
placeholdertxt.TextStrokeTransparency = 0.000
placeholdertxt.TextWrapped = true

placeholderlayout.Name = "placeholderlayout"
placeholderlayout.Parent = def
placeholderlayout.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
placeholderlayout.BackgroundTransparency = 1.000
placeholderlayout.BorderSizePixel = 0
placeholderlayout.Position = UDim2.new(0.546391606, 0, 0.020833334, 0)
placeholderlayout.Size = UDim2.new(0, 44, 0, 19)
placeholderlayout.Font = Enum.Font.SourceSans
placeholderlayout.Text = "layout"
placeholderlayout.TextColor3 = Color3.fromRGB(255, 192, 192)
placeholderlayout.TextScaled = true
placeholderlayout.TextSize = 14.000
placeholderlayout.TextStrokeTransparency = 0.000
placeholderlayout.TextWrapped = true

placeholdertime.Name = "placeholdertime"
placeholdertime.Parent = def
placeholdertime.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
placeholdertime.BackgroundTransparency = 1.000
placeholdertime.BorderSizePixel = 0
placeholdertime.Position = UDim2.new(0.556391597, 0, 0.416666657, 0)
placeholdertime.Size = UDim2.new(0, 44, 0, 28)
placeholdertime.Font = Enum.Font.SourceSans
placeholdertime.Text = "time"
placeholdertime.TextColor3 = Color3.fromRGB(230, 230, 230)
placeholdertime.TextScaled = true
placeholdertime.TextSize = 14.000
placeholdertime.TextStrokeTransparency = 0.000
placeholdertime.TextWrapped = true

realimg.Parent = def
realimg.Name = "realimg"
realimg.Visible = false

local selectedTK = nil

function createframe(ptime,ptext,pimg)
	local cloned = def:Clone()
	cloned.Name = "default"
	cloned.LayoutOrder = #editscroll:GetChildren() - 1
	cloned.Visible = true
	cloned.Parent = editscroll
	cloned.placeholdertime.Text = ptime or '0'
	cloned.placeholdertxt.Text =  ptext or ''
	cloned.realimg.Text = pimg
	cloned.placeholderimg.Image = string.format("rbxthumb://type=Asset&id=%s&w=420&h=420",pimg) or 'rbxassetid://0'
	cloned.placeholderlayout.Text = tostring(cloned.LayoutOrder)
	cloned.placeholderimg.MouseButton1Down:Connect(function()
		selectedTK = cloned
		for i,v in pairs(editscroll:GetChildren()) do 
			if not v:IsA("UIGridLayout") and v.Name ~= "def" then 
				v.BorderColor3 = Color3.fromRGB(113, 113, 113)
			end
		end
		cloned.BorderColor3 = Color3.fromRGB(10,140,255)
		textureidtb.Text = cloned.realimg.Text
		waittb.Text = cloned.placeholdertime.Text
		textlb.Text = cloned.placeholdertxt.Text
	end)
	return cloned
end

filedefault.Name = "filedefault"
filedefault.Parent = ScrollingFrame
filedefault.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
filedefault.BorderSizePixel = 0
filedefault.Size = UDim2.new(0, 147, 0, 28)
filedefault.Visible = false
filedefault.Font = Enum.Font.SourceSans
filedefault.TextColor3 = Color3.fromRGB(0, 0, 0)
filedefault.TextSize = 14.000

filename.Name = "filename"
filename.Parent = filedefault
filename.BackgroundColor3 = Color3.fromRGB(235, 235, 235)
filename.BorderSizePixel = 0
filename.Position = UDim2.new(0.183673471, 0, 0, 0)
filename.Size = UDim2.new(0, 120, 0, 28)
filename.Font = Enum.Font.SourceSans
filename.Text = "file name"
filename.TextColor3 = Color3.fromRGB(0, 0, 0)
filename.TextScaled = true
filename.TextSize = 14.000
filename.TextWrapped = true
filename.TextXAlignment = Enum.TextXAlignment.Right

fileicon.Name = "fileicon"
fileicon.Parent = filename
fileicon.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
fileicon.BorderSizePixel = 0
fileicon.Position = UDim2.new(-0.224999994, 0, 0, 0)
fileicon.Size = UDim2.new(0, 28, 0, 28)
fileicon.ResampleMode = Enum.ResamplerMode.Pixelated
fileicon.Image = "http://www.roblox.com/asset/?id=9439844549"

local selectedfile = nil

function xloadFile(_table)
	for i,v in pairs(editscroll:GetChildren()) do 
		if not v:IsA("UIGridLayout") and v.Name ~= "def" then 
			v:Destroy()
		end
	end
	if _table.config.looping == true then 
		checklooped.Visible = true
		checklooped.Image = "http://www.roblox.com/asset/?id=9398101174"
	else 
		checklooped.Visible = false
		checklooped.Image = "0"
	end
	local animorder = {}
	
	for i,v in pairs(_table.anim) do 
		animorder[v.index_] = v
	end
	for i,v in pairs(animorder) do 
	    createframe(v.sleep,v.text,v.id)
	end
end

function createFile(_filename)
	local cloned = filedefault:Clone()
	local clone2 = filename:Clone()
	local clone3 = fileicon:Clone()
	clone3.Parent = clone2
	clone2.Parent = cloned
	cloned.Parent = ScrollingFrame
	cloned.Visible = true
	cloned.filename.Text = _filename
	ScrollingFrame.CanvasSize = ScrollingFrame.CanvasSize + UDim2.new(0,0,1.15,0)
	local file,extension = readfile(_filename), tostring(string.split(tostring(_filename),".")[2])
	printconsole(extension)
	if extension == "rmas" then 
		cloned.filename.fileicon.Image = "http://www.roblox.com/asset/?id=9439887949"
	elseif extension == "json" then 
		cloned.filename.fileicon.Image = "http://www.roblox.com/asset/?id=9439864635"
	elseif extension == "txt" then 
		cloned.filename.fileicon.Image = "http://www.roblox.com/asset/?id=9439851090"
	elseif isfolder(_filename) then
		cloned.filename.fileicon.Image = "http://www.roblox.com/asset/?id=9439857554"
	else 
		cloned.filename.fileicon.Image = "http://www.roblox.com/asset/?id=9439844549"
	end
	cloned.MouseButton1Click:Connect(function()
		if not isfolder(_filename) then
			local s,r = pcall(game:GetService("HttpService").JSONDecode,file)
			local valid = false
			if s and r then 
				pcall(function()
					if r.config and r.config.file and r.config.file == ".RMAS" then 
						valid = true
					end
				end)
			end
			if string.lower(extension):match("rmas") then 
				valid = true
			end
			if valid then
				selectedfile = game:GetService("HttpService"):JSONDecode(readfile(_filename))
				descriptiono.Text = selectedfile["config"].description
				nameo.Text = selectedfile["config"].name
			end
		else
			for i,v in pairs(ScrollingFrame:GetChildren()) do 
				if not v:IsA("UiCorner") and not v:IsA("UIListLayout") then 
					v:Destroy()
				end
			end
			for i,v in pairs(listfiles(_filename)) do 
				createFile(v)
			end
		end
	end)
	buttonfy(cloned,cloned.filename)
end


openTab.Name = "openTab"
openTab.Parent = main
openTab.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
openTab.BackgroundTransparency = 1.000
openTab.Size = UDim2.new(0, 440, 0, 187)
openTab.Visible = false

rootbtn.Name = "rootbtn"
rootbtn.Parent = openTab
rootbtn.BackgroundColor3 = Color3.fromRGB(0, 0, 0)
rootbtn.BorderSizePixel = 5
rootbtn.Position = UDim2.new(0.636363626, 0, 0.0213903747, 0)
rootbtn.Size = UDim2.new(0, 136, 0, 17)
rootbtn.Font = Enum.Font.SourceSans
rootbtn.Text = ""
rootbtn.TextColor3 = Color3.fromRGB(0, 0, 0)
rootbtn.TextSize = 14.000
buttonfy(rootbtn,rootbtnlb)
rootbtn.MouseButton1Down:Connect(function()
    for i,v in pairs(ScrollingFrame:GetChildren()) do 
		if not v:IsA("UiCorner") and not v:IsA("UIListLayout") then 
			v:Destroy()
		end
	end
	for i,v in pairs(listfiles("")) do 
		createFile(v)
		wait()
	end
end)

rootcorner1.CornerRadius = UDim.new(0, 4)
rootcorner1.Name = "rootcorner1"
rootcorner1.Parent = rootbtn

rootbtndec.Name = "rootbtndec"
rootbtndec.Parent = rootbtn
rootbtndec.BackgroundColor3 = Color3.fromRGB(182, 182, 182)
rootbtndec.Size = UDim2.new(0, 136, 0, 17)

rootcorner2.CornerRadius = UDim.new(0, 4)
rootcorner2.Name = "rootcorner2"
rootcorner2.Parent = rootbtndec

rootbtnlb.Name = "rootbtnlb"
rootbtnlb.Parent = rootbtndec
rootbtnlb.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
rootbtnlb.Position = UDim2.new(0, 1, 0, 1)
rootbtnlb.Selectable = true
rootbtnlb.Size = UDim2.new(0, 134, 0, 15)
rootbtnlb.Font = Enum.Font.SourceSans
rootbtnlb.Text = "Root"
rootbtnlb.TextColor3 = Color3.fromRGB(0, 0, 0)
rootbtnlb.TextSize = 14.000

rootcorner3.CornerRadius = UDim.new(0, 4)
rootcorner3.Name = "rootcorner3"
rootcorner3.Parent = rootbtnlb

openbtn.Name = "openbtn"
openbtn.Parent = openTab
openbtn.BackgroundColor3 = Color3.fromRGB(0, 0, 0)
openbtn.BorderSizePixel = 5
openbtn.Position = UDim2.new(0.647727251, 0, 0.737967908, 0)
openbtn.Size = UDim2.new(0, 136, 0, 30)
openbtn.Font = Enum.Font.SourceSans
openbtn.Text = ""
openbtn.TextColor3 = Color3.fromRGB(0, 0, 0)
openbtn.TextSize = 14.000
buttonfy(openbtn,openbtnlb)
openbtn.MouseButton1Down:Connect(function()
	xloadFile(selectedfile)
end)

UICorner_8.CornerRadius = UDim.new(0, 4)
UICorner_8.Parent = openbtn

openbtndec.Name = "openbtndec"
openbtndec.Parent = openbtn
openbtndec.BackgroundColor3 = Color3.fromRGB(182, 182, 182)
openbtndec.Size = UDim2.new(0, 136, 0, 30)

UICorner_9.CornerRadius = UDim.new(0, 4)
UICorner_9.Parent = openbtndec

openbtnlb.Name = "openbtnlb"
openbtnlb.Parent = openbtndec
openbtnlb.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
openbtnlb.Position = UDim2.new(0, 1, 0, 1)
openbtnlb.Selectable = true
openbtnlb.Size = UDim2.new(0, 134, 0, 28)
openbtnlb.Font = Enum.Font.SourceSans
openbtnlb.Text = "Open"
openbtnlb.TextColor3 = Color3.fromRGB(0, 0, 0)
openbtnlb.TextSize = 14.000

UICorner_10.CornerRadius = UDim.new(0, 4)
UICorner_10.Parent = openbtnlb

namelbo.Name = "namelbo"
namelbo.Parent = openTab
namelbo.BackgroundColor3 = Color3.fromRGB(182, 182, 182)
namelbo.Position = UDim2.new(0.645454526, 0, 0.133689836, 0)
namelbo.Size = UDim2.new(0, 138, 0, 26)
namelbo.Font = Enum.Font.SourceSans
namelbo.TextColor3 = Color3.fromRGB(0, 0, 0)
namelbo.TextSize = 14.000

nameo.Name = "nameo"
nameo.Parent = namelbo
nameo.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
nameo.BorderColor3 = Color3.fromRGB(200, 200, 200)
nameo.Position = UDim2.new(0, 1, 0, 1)
nameo.Size = UDim2.new(0, 136, 0, 24)
nameo.ClearTextOnFocus = false
nameo.Font = Enum.Font.SourceSans
nameo.PlaceholderColor3 = Color3.fromRGB(68, 68, 68)
nameo.PlaceholderText = "Name"
nameo.Text = ""
nameo.TextColor3 = Color3.fromRGB(0, 0, 0)
nameo.TextSize = 14.000
nameo.TextWrapped = true
nameo.TextEditable = false

UICorner_11.CornerRadius = UDim.new(0, 4)
UICorner_11.Parent = nameo

UICorner_12.CornerRadius = UDim.new(0, 4)
UICorner_12.Parent = namelbo

descriptionlbo.Name = "descriptionlbo"
descriptionlbo.Parent = openTab
descriptionlbo.BackgroundColor3 = Color3.fromRGB(182, 182, 182)
descriptionlbo.Position = UDim2.new(0.645454526, 0, 0.331550807, 0)
descriptionlbo.Size = UDim2.new(0, 138, 0, 62)
descriptionlbo.Font = Enum.Font.SourceSans
descriptionlbo.TextColor3 = Color3.fromRGB(0, 0, 0)
descriptionlbo.TextSize = 14.000

descriptiono.Name = "descriptiono"
descriptiono.Parent = descriptionlbo
descriptiono.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
descriptiono.BorderColor3 = Color3.fromRGB(200, 200, 200)
descriptiono.Position = UDim2.new(0, 1, 0, 1)
descriptiono.Size = UDim2.new(0, 136, 0, 60)
descriptiono.ClearTextOnFocus = false
descriptiono.Font = Enum.Font.SourceSans
descriptiono.PlaceholderColor3 = Color3.fromRGB(68, 68, 68)
descriptiono.PlaceholderText = "Description"
descriptiono.Text = ""
descriptiono.TextColor3 = Color3.fromRGB(0, 0, 0)
descriptiono.TextSize = 14.000
descriptiono.TextWrapped = true
descriptiono.TextEditable = false

UICorner_13.CornerRadius = UDim.new(0, 4)
UICorner_13.Parent = descriptiono

UICorner_14.CornerRadius = UDim.new(0, 4)
UICorner_14.Parent = descriptionlbo

scrolldec.Name = "scrolldec"
scrolldec.Parent = openTab
scrolldec.BackgroundColor3 = Color3.fromRGB(184, 184, 184)
scrolldec.Position = UDim2.new(0.272727251, 0, 0.112299465, 0)
scrolldec.Size = UDim2.new(0, 162, 0, 144)

UICorner_15.CornerRadius = UDim.new(0, 4)
UICorner_15.Parent = scrolldec

ScrollingFrame.Parent = scrolldec
ScrollingFrame.Active = true
ScrollingFrame.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
ScrollingFrame.BorderColor3 = Color3.fromRGB(255, 255, 255)
ScrollingFrame.Position = UDim2.new(0, 2, 0, 2)
ScrollingFrame.Size = UDim2.new(0, 158, 0, 140)
ScrollingFrame.ScrollBarThickness = 8
ScrollingFrame.ScrollBarImageColor3 = Color3.fromRGB(0,0,0)

UIListLayout.Parent = ScrollingFrame
UIListLayout.SortOrder = Enum.SortOrder.LayoutOrder

UICorner_16.CornerRadius = UDim.new(0, 4)
UICorner_16.Parent = ScrollingFrame

df.Name = "df"
df.Parent = ScrollingFrame
df.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
df.BorderColor3 = Color3.fromRGB(234, 234, 234)
df.Size = UDim2.new(0, 147, 0, 23)
df.Visible = false

dflabel.Name = "dflabel"
dflabel.Parent = df
dflabel.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
dflabel.BackgroundTransparency = 255.000
dflabel.Size = UDim2.new(0, 130, 0, 23)
dflabel.Font = Enum.Font.SourceSans
dflabel.Text = "name"
dflabel.TextColor3 = Color3.fromRGB(0, 0, 0)
dflabel.TextSize = 14.000

mainlist.Name = "mainlist"
mainlist.Parent = main
mainlist.BackgroundColor3 = Color3.fromRGB(242, 242, 242)
mainlist.BorderSizePixel = 0
mainlist.Position = UDim2.new(0, 0, 0.00258305995, 0)
mainlist.Size = UDim2.new(0, 111, 0, 187)

svlistbtn.Name = "svlistbtn"
svlistbtn.Parent = mainlist
svlistbtn.BackgroundColor3 = Color3.fromRGB(182, 182, 182)
svlistbtn.BorderSizePixel = 0
svlistbtn.LayoutOrder = 4
svlistbtn.Size = UDim2.new(0, 111, 0, 36)
svlistbtn.Font = Enum.Font.SourceSans
svlistbtn.TextColor3 = Color3.fromRGB(0, 0, 0)
svlistbtn.TextSize = 14.000
svlistbtn.MouseEnter:Connect(function()
	if svlistlb.BackgroundColor3 ~= Color3.fromRGB(255,255,255) then 
		svlistlb.BackgroundColor3 = Color3.fromRGB(228, 238, 254)
	end
end)
svlistbtn.MouseLeave:Connect(function()
	if svlistlb.BackgroundColor3 ~= Color3.fromRGB(255, 255, 255) then 
		svlistlb.BackgroundColor3 = Color3.fromRGB(242, 242, 242)
	end 
end)

svlistbtn.MouseButton1Down:Connect(function()
	for i,v in pairs(mainlist:GetChildren()) do 
		if v:IsA("TextButton") then 
			v:GetChildren()[1]:GetChildren()[1].BackgroundColor3 = Color3.fromRGB(242,242,242)
			v:GetChildren()[1]:GetChildren()[1]:GetChildren()[1].Visible = false
		end
	end
	for i,v in pairs(main:GetChildren()) do 
		if not v.Name:match("list") then 
			v.Visible = false
		end
	end
	saveTab.Visible = true
	svlistlb.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
	svasel.Visible = true
	title.Text = "Rate My Avatar - Save"
end)

svlist.Name = "svlist"
svlist.Parent = svlistbtn
svlist.BackgroundColor3 = Color3.fromRGB(182, 182, 182)
svlist.BorderSizePixel = 0
svlist.Size = UDim2.new(0, 111, 0, 37)
svlist.Font = Enum.Font.SourceSans
svlist.TextColor3 = Color3.fromRGB(0, 0, 0)
svlist.TextSize = 14.000

svlistlb.Name = "svlistlb"
svlistlb.Parent = svlist
svlistlb.BackgroundColor3 = Color3.fromRGB(242, 242, 242)
svlistlb.BorderSizePixel = 0
svlistlb.Position = UDim2.new(0, 1, 0, 1)
svlistlb.Size = UDim2.new(0, 109, 0, 35)
svlistlb.Font = Enum.Font.SourceSans
svlistlb.Text = "Save"
svlistlb.TextColor3 = Color3.fromRGB(0, 0, 0)
svlistlb.TextSize = 14.000

svasel.Name = "svasel"
svasel.Parent = svlistlb
svasel.BackgroundColor3 = Color3.fromRGB(242, 242, 242)
svasel.BorderColor3 = Color3.fromRGB(182, 182, 182)
svasel.Size = UDim2.new(0, 7, 0, 35)
svasel.Visible = false
svasel.ZIndex = 5

UIListLayout_2.Parent = mainlist
UIListLayout_2.SortOrder = Enum.SortOrder.LayoutOrder

oplistbtn.Name = "oplistbtn"
oplistbtn.Parent = mainlist
oplistbtn.BackgroundColor3 = Color3.fromRGB(182, 182, 182)
oplistbtn.BorderSizePixel = 0
oplistbtn.LayoutOrder = 3
oplistbtn.Size = UDim2.new(0, 111, 0, 36)
oplistbtn.Font = Enum.Font.SourceSans
oplistbtn.TextColor3 = Color3.fromRGB(0, 0, 0)
oplistbtn.TextSize = 14.000
oplistbtn.MouseEnter:Connect(function()
	if oplistlb.BackgroundColor3 ~= Color3.fromRGB(255,255,255) then 
		oplistlb.BackgroundColor3 = Color3.fromRGB(228, 238, 254)
	end
end)
oplistbtn.MouseLeave:Connect(function()
	if oplistlb.BackgroundColor3 ~= Color3.fromRGB(255, 255, 255) then 
		oplistlb.BackgroundColor3 = Color3.fromRGB(242, 242, 242)
	end
end)
oplistbtn.MouseButton1Down:Connect(function()
	for i,v in pairs(mainlist:GetChildren()) do 
		if v:IsA("TextButton") then 
			v:GetChildren()[1]:GetChildren()[1].BackgroundColor3 = Color3.fromRGB(242,242,242)
			v:GetChildren()[1]:GetChildren()[1]:GetChildren()[1].Visible = false
		end
	end
	for i,v in pairs(main:GetChildren()) do 
		if not v.Name:match("list") then 
			v.Visible = false
		end
	end
	openTab.Visible = true
	oplistlb.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
	opasel.Visible = true
	title.Text = "Rate My Avatar - Open"
	for i,v in pairs(ScrollingFrame:GetChildren()) do 
		if not v:IsA("UiCorner") and not v:IsA("UIListLayout") then 
			v:Destroy()
		end
	end
	for i,v in pairs(listfiles("")) do 
		createFile(v)
		wait()
	end
end)

oplist.Name = "oplist"
oplist.Parent = oplistbtn
oplist.BackgroundColor3 = Color3.fromRGB(182, 182, 182)
oplist.BorderSizePixel = 0
oplist.Size = UDim2.new(0, 111, 0, 37)
oplist.Font = Enum.Font.SourceSans
oplist.TextColor3 = Color3.fromRGB(0, 0, 0)
oplist.TextSize = 14.000

oplistlb.Name = "oplistlb"
oplistlb.Parent = oplist
oplistlb.BackgroundColor3 = Color3.fromRGB(242, 242, 242)
oplistlb.BorderSizePixel = 0
oplistlb.Position = UDim2.new(0, 1, 0, 1)
oplistlb.Size = UDim2.new(0, 109, 0, 35)
oplistlb.Font = Enum.Font.SourceSans
oplistlb.Text = "Open"
oplistlb.TextColor3 = Color3.fromRGB(0, 0, 0)
oplistlb.TextSize = 14.000

opasel.Name = "opasel"
opasel.Parent = oplistlb
opasel.BackgroundColor3 = Color3.fromRGB(242, 242, 242)
opasel.BorderColor3 = Color3.fromRGB(182, 182, 182)
opasel.Size = UDim2.new(0, 7, 0, 35)
opasel.Visible = false
opasel.ZIndex = 5

edlistbtn.Name = "edlistbtn"
edlistbtn.Parent = mainlist
edlistbtn.BackgroundColor3 = Color3.fromRGB(182, 182, 182)
edlistbtn.BorderSizePixel = 0
edlistbtn.LayoutOrder = 2
edlistbtn.Size = UDim2.new(0, 111, 0, 36)
edlistbtn.Font = Enum.Font.SourceSans
edlistbtn.TextColor3 = Color3.fromRGB(0, 0, 0)
edlistbtn.TextSize = 14.000
edlistbtn.MouseEnter:Connect(function()
	if edlistlb.BackgroundColor3 ~= Color3.fromRGB(255,255,255) then 
		edlistlb.BackgroundColor3 = Color3.fromRGB(228, 238, 254)
	end
end)

edlistbtn.MouseLeave:Connect(function()
	if edlistlb.BackgroundColor3 ~= Color3.fromRGB(255, 255, 255) then 
		edlistlb.BackgroundColor3 = Color3.fromRGB(242, 242, 242)
	end
end)
edlistbtn.MouseButton1Down:Connect(function()
	for i,v in pairs(mainlist:GetChildren()) do 
		if v:IsA("TextButton") then 
			v:GetChildren()[1]:GetChildren()[1].BackgroundColor3 = Color3.fromRGB(242,242,242)
			v:GetChildren()[1]:GetChildren()[1]:GetChildren()[1].Visible = false
		end
	end
	for i,v in pairs(main:GetChildren()) do 
		if not v.Name:match("list") then 
			v.Visible = false
		end
	end
	editTab.Visible = true
	edlistlb.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
	edasel.Visible = true
	title.Text = "Rate My Avatar - Edit"
end)

edlist.Name = "edlist"
edlist.Parent = edlistbtn
edlist.BackgroundColor3 = Color3.fromRGB(182, 182, 182)
edlist.BorderSizePixel = 0
edlist.Size = UDim2.new(0, 111, 0, 37)
edlist.Font = Enum.Font.SourceSans
edlist.TextColor3 = Color3.fromRGB(0, 0, 0)
edlist.TextSize = 14.000

edlistlb.Name = "edlistlb"
edlistlb.Parent = edlist
edlistlb.BackgroundColor3 = Color3.fromRGB(242, 242, 242)
edlistlb.BorderSizePixel = 0
edlistlb.Position = UDim2.new(0, 1, 0, 1)
edlistlb.Size = UDim2.new(0, 109, 0, 35)
edlistlb.Font = Enum.Font.SourceSans
edlistlb.Text = "Edit"
edlistlb.TextColor3 = Color3.fromRGB(0, 0, 0)
edlistlb.TextSize = 14.000

edasel.Name = "edasel"
edasel.Parent = edlistlb
edasel.BackgroundColor3 = Color3.fromRGB(242, 242, 242)
edasel.BorderColor3 = Color3.fromRGB(182, 182, 182)
edasel.Size = UDim2.new(0, 7, 0, 35)
edasel.Visible = false
edasel.ZIndex = 5

menubtn.Name = "menubtn"
menubtn.Parent = mainlist
menubtn.BackgroundColor3 = Color3.fromRGB(182, 182, 182)
menubtn.BorderSizePixel = 0
menubtn.LayoutOrder = 1
menubtn.Size = UDim2.new(0, 111, 0, 36)
menubtn.Font = Enum.Font.SourceSans
menubtn.TextColor3 = Color3.fromRGB(0, 0, 0)
menubtn.TextSize = 14.000
menubtn.MouseEnter:Connect(function()
	if menulistlb.BackgroundColor3 ~= Color3.fromRGB(255,255,255) then 
		menulistlb.BackgroundColor3 = Color3.fromRGB(228, 238, 254)
	end
end)

menubtn.MouseLeave:Connect(function()
	if menulistlb.BackgroundColor3 ~= Color3.fromRGB(255, 255, 255) then 
		menulistlb.BackgroundColor3 = Color3.fromRGB(242, 242, 242)
	end
end)
menubtn.MouseButton1Down:Connect(function()
	for i,v in pairs(mainlist:GetChildren()) do 
		if v:IsA("TextButton") then 
			v:GetChildren()[1]:GetChildren()[1].BackgroundColor3 = Color3.fromRGB(242,242,242)
			v:GetChildren()[1]:GetChildren()[1]:GetChildren()[1].Visible = false
		end
	end
	for i,v in pairs(main:GetChildren()) do 
		if not v.Name:match("list") then 
			v.Visible = false
		end
	end
	menuTab.Visible = true
	menulistlb.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
	menuasel.Visible = true
	title.Text = "Rate My Avatar - Menu"
end)


menulist.Name = "menulist"
menulist.Parent = menubtn
menulist.BackgroundColor3 = Color3.fromRGB(182, 182, 182)
menulist.BorderSizePixel = 0
menulist.Size = UDim2.new(0, 111, 0, 37)
menulist.Font = Enum.Font.SourceSans
menulist.TextColor3 = Color3.fromRGB(0, 0, 0)
menulist.TextSize = 14.000

menulistlb.Name = "menulistlb"
menulistlb.Parent = menulist
menulistlb.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
menulistlb.BorderSizePixel = 0
menulistlb.Position = UDim2.new(0, 1, 0, 1)
menulistlb.Size = UDim2.new(0, 109, 0, 35)
menulistlb.Font = Enum.Font.SourceSans
menulistlb.Text = "Menu"
menulistlb.TextColor3 = Color3.fromRGB(0, 0, 0)
menulistlb.TextSize = 14.000

menuasel.Name = "menuasel"
menuasel.Parent = menulistlb
menuasel.BackgroundColor3 = Color3.fromRGB(242, 242, 242)
menuasel.BorderColor3 = Color3.fromRGB(182, 182, 182)
menuasel.Size = UDim2.new(0, 7, 0, 35)
menuasel.ZIndex = 5

editTab.Name = "editTab"
editTab.Parent = main
editTab.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
editTab.BackgroundTransparency = 1.000
editTab.Size = UDim2.new(0, 440, 0, 187)
editTab.Visible = false

loopedcheck.Name = "loopedcheck"
loopedcheck.Parent = editTab
loopedcheck.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
loopedcheck.BackgroundTransparency = 1.000
loopedcheck.BorderSizePixel = 0
loopedcheck.Position = UDim2.new(0.272727281, 0, 0.893048167, 0)
loopedcheck.Size = UDim2.new(0, 71, 0, 10)
loopedcheck.Font = Enum.Font.SourceSans
loopedcheck.Text = "Looped"
loopedcheck.TextColor3 = Color3.fromRGB(0, 0, 0)
loopedcheck.TextSize = 14.000
loopedcheck.MouseEnter:Connect(function()
	loopedchecklb.BackgroundColor3 = Color3.fromRGB(228, 238, 254)
end)
loopedcheck.MouseLeave:Connect(function()
	loopedchecklb.BackgroundColor3 = Color3.fromRGB(255,255,255)
end)
loopedcheck.MouseButton1Down:Connect(function()
	checklooped.Visible = not checklooped.Visible
	if checklooped.Image ~= "http://www.roblox.com/asset/?id=9398101174" then 
		checklooped.Image = "http://www.roblox.com/asset/?id=9398101174"
	else
		checklooped.Image = "0"
	end
end)

loopedchecklb.Name = "loopedchecklb"
loopedchecklb.Parent = loopedcheck
loopedchecklb.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
loopedchecklb.BorderColor3 = Color3.fromRGB(182, 182, 182)
loopedchecklb.Size = UDim2.new(0, 10, 0, 10)

checklooped.Name = "checklooped"
checklooped.Parent = loopedchecklb
checklooped.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
checklooped.BorderColor3 = Color3.fromRGB(182, 182, 182)
checklooped.Size = UDim2.new(0, 10, 0, 10)
checklooped.Image = "http://www.roblox.com/asset/?id=9398101174"

Frame.Parent = editTab
Frame.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
Frame.BackgroundTransparency = 1.000
Frame.Position = UDim2.new(0.822727323, 0, 0.0320855603, 0)
Frame.Size = UDim2.new(0, 77, 0, 131)

UIListLayout_3.Parent = Frame
UIListLayout_3.SortOrder = Enum.SortOrder.LayoutOrder
UIListLayout_3.Padding = UDim.new(0, 4)

deletebtn.Name = "deletebtn"
deletebtn.Parent = Frame
deletebtn.BackgroundColor3 = Color3.fromRGB(0, 0, 0)
deletebtn.BorderSizePixel = 5
deletebtn.LayoutOrder = 3
deletebtn.Position = UDim2.new(0.804545403, 0, 0.401069492, 0)
deletebtn.Size = UDim2.new(0, 77, 0, 30)
deletebtn.Font = Enum.Font.SourceSans
deletebtn.Text = ""
deletebtn.TextColor3 = Color3.fromRGB(0, 0, 0)
deletebtn.TextSize = 14.000
buttonfy(deletebtn,deletebtnlb)
deletebtn.MouseButton1Down:Connect(function()
	if selectedTK ~= nil then
		selectedTK:Destroy()
	end
	selectedTK = nil
end)

UICorner_17.CornerRadius = UDim.new(0, 4)
UICorner_17.Parent = deletebtn

deletebtndec.Name = "deletebtndec"
deletebtndec.Parent = deletebtn
deletebtndec.BackgroundColor3 = Color3.fromRGB(182, 182, 182)
deletebtndec.Size = UDim2.new(0, 77, 0, 30)

UICorner_18.CornerRadius = UDim.new(0, 4)
UICorner_18.Parent = deletebtndec

deletebtnlb.Name = "deletebtnlb"
deletebtnlb.Parent = deletebtndec
deletebtnlb.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
deletebtnlb.Position = UDim2.new(0, 1, 0, 1)
deletebtnlb.Selectable = true
deletebtnlb.Size = UDim2.new(0, 75, 0, 28)
deletebtnlb.Font = Enum.Font.SourceSans
deletebtnlb.Text = "Delete Frame"
deletebtnlb.TextColor3 = Color3.fromRGB(0, 0, 0)
deletebtnlb.TextSize = 14.000

UICorner_19.CornerRadius = UDim.new(0, 4)
UICorner_19.Parent = deletebtnlb

newfrbtn.Name = "newfrbtn"
newfrbtn.Parent = Frame
newfrbtn.BackgroundColor3 = Color3.fromRGB(0, 0, 0)
newfrbtn.BorderSizePixel = 5
newfrbtn.LayoutOrder = 2
newfrbtn.Position = UDim2.new(0.804545403, 0, 0.224598944, 0)
newfrbtn.Size = UDim2.new(0, 77, 0, 30)
newfrbtn.Font = Enum.Font.SourceSans
newfrbtn.Text = ""
newfrbtn.TextColor3 = Color3.fromRGB(0, 0, 0)
newfrbtn.TextSize = 14.000
buttonfy(newfrbtn,newfrbtnlb)
newfrbtn.MouseButton1Down:Connect(function()
	selectedTK = createframe(waittb.Text,texttb.Text, textureidtb.Text)
	for i,v in pairs(editscroll:GetChildren()) do 
		if not v:IsA("UIGridLayout") and v.Name ~= "def" then 
			v.BorderColor3 = Color3.fromRGB(113, 113, 113)
		end
	end
	selectedTK.BorderColor3 = Color3.fromRGB(10,140,255)
end)

UICorner_20.CornerRadius = UDim.new(0, 4)
UICorner_20.Parent = newfrbtn

newfrbtndec.Name = "newfrbtndec"
newfrbtndec.Parent = newfrbtn
newfrbtndec.BackgroundColor3 = Color3.fromRGB(182, 182, 182)
newfrbtndec.Size = UDim2.new(0, 77, 0, 30)

UICorner_21.CornerRadius = UDim.new(0, 4)
UICorner_21.Parent = newfrbtndec

newfrbtnlb.Name = "newfrbtnlb"
newfrbtnlb.Parent = newfrbtndec
newfrbtnlb.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
newfrbtnlb.Position = UDim2.new(0, 1, 0, 1)
newfrbtnlb.Selectable = true
newfrbtnlb.Size = UDim2.new(0, 75, 0, 28)
newfrbtnlb.Font = Enum.Font.SourceSans
newfrbtnlb.Text = "New Frame"
newfrbtnlb.TextColor3 = Color3.fromRGB(0, 0, 0)
newfrbtnlb.TextSize = 14.000

UICorner_22.CornerRadius = UDim.new(0, 4)
UICorner_22.Parent = newfrbtnlb

updatebtn.Name = "updatebtn"
updatebtn.Parent = Frame
updatebtn.BackgroundColor3 = Color3.fromRGB(0, 0, 0)
updatebtn.BorderSizePixel = 5
updatebtn.LayoutOrder = 3
updatebtn.Position = UDim2.new(0.804545403, 0, 0.401069492, 0)
updatebtn.Size = UDim2.new(0, 77, 0, 30)
updatebtn.Font = Enum.Font.SourceSans
updatebtn.Text = ""
updatebtn.TextColor3 = Color3.fromRGB(0, 0, 0)
updatebtn.TextSize = 14.000
buttonfy(updatebtn,updatebtnlb)
updatebtn.MouseButton1Down:Connect(function()
	if selectedTK ~= nil then 
		selectedTK.realimg.Text = textureidtb.Text
		selectedTK.placeholderimg.Image = string.format("rbxthumb://type=Asset&id=%s&w=420&h=420",textureidtb.Text)
		selectedTK.placeholdertime.Text = waittb.Text
		selectedTK.placeholdertxt.Text = texttb.Text
	end	
end)

UICorner_23.CornerRadius = UDim.new(0, 4)
UICorner_23.Parent = updatebtn

updatebtndec.Name = "updatebtndec"
updatebtndec.Parent = updatebtn
updatebtndec.BackgroundColor3 = Color3.fromRGB(182, 182, 182)
updatebtndec.Size = UDim2.new(0, 77, 0, 30)

UICorner_24.CornerRadius = UDim.new(0, 4)
UICorner_24.Parent = updatebtndec

updatebtnlb.Name = "updatebtnlb"
updatebtnlb.Parent = updatebtndec
updatebtnlb.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
updatebtnlb.Position = UDim2.new(0, 1, 0, 1)
updatebtnlb.Selectable = true
updatebtnlb.Size = UDim2.new(0, 75, 0, 28)
updatebtnlb.Font = Enum.Font.SourceSans
updatebtnlb.Text = "Update Frame"
updatebtnlb.TextColor3 = Color3.fromRGB(0, 0, 0)
updatebtnlb.TextSize = 14.000

UICorner_25.CornerRadius = UDim.new(0, 4)
UICorner_25.Parent = updatebtnlb

textureidlb.Name = "textureidlb"
textureidlb.Parent = editTab
textureidlb.BackgroundColor3 = Color3.fromRGB(182, 182, 182)
textureidlb.Position = UDim2.new(0.434090912, 0, 0.802139044, 0)
textureidlb.Size = UDim2.new(0, 104, 0, 31)
textureidlb.Font = Enum.Font.SourceSans
textureidlb.TextColor3 = Color3.fromRGB(0, 0, 0)
textureidlb.TextSize = 14.000

textureidtb.Name = "textureidtb"
textureidtb.Parent = textureidlb
textureidtb.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
textureidtb.BorderColor3 = Color3.fromRGB(200, 200, 200)
textureidtb.Position = UDim2.new(0, 1, 0, 1)
textureidtb.Size = UDim2.new(0, 102, 0, 29)
textureidtb.ClearTextOnFocus = false
textureidtb.Font = Enum.Font.SourceSans
textureidtb.PlaceholderColor3 = Color3.fromRGB(68, 68, 68)
textureidtb.PlaceholderText = "Decal Id"
textureidtb.Text = ""
textureidtb.TextColor3 = Color3.fromRGB(0, 0, 0)
textureidtb.TextSize = 14.000
textureidtb.TextWrapped = true
textboxify(textureidtb,textureidlb)
textureidtb:GetPropertyChangedSignal("Text"):Connect(function()
	textureidtb.Text = string.gsub(textureidtb.Text,"%D+","")
end)

UICorner_26.CornerRadius = UDim.new(0, 4)
UICorner_26.Parent = textureidtb

UICorner_27.CornerRadius = UDim.new(0, 4)
UICorner_27.Parent = textureidlb

textlb.Name = "textlb"
textlb.Parent = editTab
textlb.BackgroundColor3 = Color3.fromRGB(182, 182, 182)
textlb.Position = UDim2.new(0.690909088, 0, 0.796791434, 0)
textlb.Size = UDim2.new(0, 104, 0, 31)
textlb.Font = Enum.Font.SourceSans
textlb.TextColor3 = Color3.fromRGB(0, 0, 0)
textlb.TextSize = 14.000

texttb.Name = "texttb"
texttb.Parent = textlb
texttb.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
texttb.BorderColor3 = Color3.fromRGB(200, 200, 200)
texttb.Position = UDim2.new(0, 1, 0, 1)
texttb.Size = UDim2.new(0, 102, 0, 29)
texttb.ClearTextOnFocus = false
texttb.Font = Enum.Font.SourceSans
texttb.PlaceholderColor3 = Color3.fromRGB(68, 68, 68)
texttb.PlaceholderText = "Text"
texttb.Text = ""
texttb.TextColor3 = Color3.fromRGB(0, 0, 0)
texttb.TextSize = 14.000
texttb.TextWrapped = true
textboxify(texttb,textlb)

UICorner_28.CornerRadius = UDim.new(0, 4)
UICorner_28.Parent = texttb

UICorner_29.CornerRadius = UDim.new(0, 4)
UICorner_29.Parent = textlb

editframe.Name = "editframe"
editframe.Parent = editTab
editframe.BackgroundColor3 = Color3.fromRGB(184, 184, 184)
editframe.Position = UDim2.new(0.273000002, 0, 0.0210000109, 0)
editframe.Size = UDim2.new(0, 231, 0, 144)

UICorner_30.CornerRadius = UDim.new(0, 4)
UICorner_30.Parent = editframe

editscroll.Name = "editscroll"
editscroll.Parent = editframe
editscroll.Active = true
editscroll.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
editscroll.BorderColor3 = Color3.fromRGB(255, 255, 255)
editscroll.Position = UDim2.new(0, 2, 0, 2)
editscroll.Size = UDim2.new(0, 226, 0, 140)
editscroll.CanvasSize = UDim2.new(2, 0, 2, 0)
editscroll.ScrollBarThickness = 8
editscroll.ScrollBarImageColor3 = Color3.fromRGB(0,0,0)

UIGridLayout.Parent = editscroll
UIGridLayout.SortOrder = Enum.SortOrder.LayoutOrder
UIGridLayout.CellSize = UDim2.new(0, 100, 0, 48)

waitlb.Name = "waitlb"
waitlb.Parent = editTab
waitlb.BackgroundColor3 = Color3.fromRGB(182, 182, 182)
waitlb.Position = UDim2.new(0.824999988, 0, 0.593582869, 0)
waitlb.Size = UDim2.new(0, 76, 0, 31)
waitlb.Font = Enum.Font.SourceSans
waitlb.TextColor3 = Color3.fromRGB(0, 0, 0)
waitlb.TextSize = 14.000

waittb.Name = "waittb"
waittb.Parent = waitlb
waittb.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
waittb.BorderColor3 = Color3.fromRGB(200, 200, 200)
waittb.Position = UDim2.new(0, 1, 0, 1)
waittb.Size = UDim2.new(0, 74, 0, 29)
waittb.ClearTextOnFocus = false
waittb.Font = Enum.Font.SourceSans
waittb.PlaceholderColor3 = Color3.fromRGB(68, 68, 68)
waittb.PlaceholderText = "Time"
waittb.Text = ""
waittb.TextColor3 = Color3.fromRGB(0, 0, 0)
waittb.TextSize = 14.000
waittb.TextWrapped = true
textboxify(waittb,waitlb)
waittb:GetPropertyChangedSignal("Text"):Connect(function()
	waittb.Text = string.gsub(waittb.Text,"%.%D+","")
	if tonumber(waittb.Text) > 50 then 
		waittb.Text = 50
	end
end)

UICorner_31.CornerRadius = UDim.new(0, 4)
UICorner_31.Parent = waittb

UICorner_32.CornerRadius = UDim.new(0, 4)
UICorner_32.Parent = waitlb

local animplaying = false

function playanimation()
	local order = {}
	for i,v in pairs(editscroll:GetChildren()) do 
		if not v:IsA("UIGridLayout") and v.Name ~= "def" then 
			table.insert(order,v.LayoutOrder,v)
		end
	end
	if checklooped.Visible == false then 
		for i,v in pairs(order) do 
			if animplaying == false then break end
			wait(tonumber(v.placeholdertime.Text))
			game:GetService("ReplicatedStorage").CustomiseBooth:FireServer("Update",{["DescriptionText"]=v.placeholdertxt.Text,["ImageId"]=v.realimg.Text})
		end
	else 
		while true do 
			for i,v in pairs(order) do 
				if animplaying == false then break end
				wait(tonumber(v.placeholdertime.Text))
				game:GetService("ReplicatedStorage").CustomiseBooth:FireServer("Update",{["DescriptionText"]=v.placeholdertxt.Text,["ImageId"]=v.realimg.Text})
			end
			if animplaying == false then 
			    break
			end
		end
	end
end

pausebtn.Name = "pausebtn"
pausebtn.Parent = editTab
pausebtn.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
pausebtn.BackgroundTransparency = 1.000
pausebtn.BorderSizePixel = 0
pausebtn.Position = UDim2.new(0.272727251, 0, 0.807486653, 0)
pausebtn.Size = UDim2.new(0, 11, 0, 11)
pausebtn.Font = Enum.Font.SourceSans
pausebtn.Text = ""
pausebtn.TextColor3 = Color3.fromRGB(0, 0, 0)
pausebtn.TextSize = 14.000
pausebtn.MouseButton1Down:Connect(function()
	if animplaying == true then 
		animplaying = false
		pauselb.Image = "http://www.roblox.com/asset/?id=9398609231"
	else 
		animplaying = true 
		pauselb.Image = "http://www.roblox.com/asset/?id=9398607380"
		playanimation()
	end
end)

pauselb.Name = "pauselb"
pauselb.Parent = pausebtn
pauselb.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
pauselb.BackgroundTransparency = 1.000
pauselb.BorderSizePixel = 0
pauselb.Size = UDim2.new(0, 11, 0, 11)
pauselb.Image = "http://www.roblox.com/asset/?id=9398609231" -- http://www.roblox.com/asset/?id=9398607380

menuTab.Name = "menuTab"
menuTab.Parent = main
menuTab.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
menuTab.BackgroundTransparency = 1.000
menuTab.Size = UDim2.new(0, 440, 0, 187)

checkupdbtn.Name = "checkupdbtn"
checkupdbtn.Parent = menuTab
checkupdbtn.BackgroundColor3 = Color3.fromRGB(0, 0, 0)
checkupdbtn.BorderSizePixel = 5
checkupdbtn.Position = UDim2.new(0.647727251, 0, 0.737967908, 0)
checkupdbtn.Size = UDim2.new(0, 136, 0, 30)
checkupdbtn.Font = Enum.Font.SourceSans
checkupdbtn.Text = ""
checkupdbtn.TextColor3 = Color3.fromRGB(0, 0, 0)
checkupdbtn.TextSize = 14.000

UICorner_33.CornerRadius = UDim.new(0, 4)
UICorner_33.Parent = checkupdbtn

checkupdbtndec.Name = "checkupdbtndec"
checkupdbtndec.Parent = checkupdbtn
checkupdbtndec.BackgroundColor3 = Color3.fromRGB(182, 182, 182)
checkupdbtndec.Size = UDim2.new(0, 136, 0, 30)

UICorner_34.CornerRadius = UDim.new(0, 4)
UICorner_34.Parent = checkupdbtndec

checkupdbtnlb.Name = "checkupdbtnlb"
checkupdbtnlb.Parent = checkupdbtndec
checkupdbtnlb.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
checkupdbtnlb.Position = UDim2.new(0, 1, 0, 1)
checkupdbtnlb.Selectable = true
checkupdbtnlb.Size = UDim2.new(0, 134, 0, 28)
checkupdbtnlb.Font = Enum.Font.SourceSans
checkupdbtnlb.Text = "Check for updates"
checkupdbtnlb.TextColor3 = Color3.fromRGB(0, 0, 0)
checkupdbtnlb.TextSize = 14.000

UICorner_35.CornerRadius = UDim.new(0, 4)
UICorner_35.Parent = checkupdbtnlb

credits.Name = "credits"
credits.Parent = menuTab
credits.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
credits.BackgroundTransparency = 1.000
credits.Position = UDim2.new(0.272727281, 0, 0.053475935, 0)
credits.Size = UDim2.new(0, 311, 0, 26)
credits.Font = Enum.Font.SourceSans
credits.Text = "Made by awesomedude939"
credits.TextColor3 = Color3.fromRGB(0, 0, 0)
credits.TextSize = 14.000

versiondetected.Name = "versiondetected"
versiondetected.Parent = menuTab
versiondetected.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
versiondetected.BackgroundTransparency = 1.000
versiondetected.Position = UDim2.new(0.272727281, 0, 0.192513362, 0)
versiondetected.Size = UDim2.new(0, 311, 0, 26)
versiondetected.Font = Enum.Font.SourceSans
versiondetected.Text = "Version 1.0.0"
versiondetected.TextColor3 = Color3.fromRGB(0, 0, 0)
versiondetected.TextSize = 14.000

warnings.Name = "warnings"
warnings.Parent = menuTab
warnings.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
warnings.BackgroundTransparency = 1.000
warnings.Position = UDim2.new(0.272727281, 0, 0.598930478, 0)
warnings.Size = UDim2.new(0, 311, 0, 26)
warnings.Visible = false
warnings.Font = Enum.Font.SourceSansBold
warnings.Text = "You are using an unofficial version or an outdated version."
warnings.TextColor3 = Color3.fromRGB(255, 0, 0)
warnings.TextSize = 14.000

closebtn.Name = "closebtn"
closebtn.Parent = bar
closebtn.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
closebtn.BackgroundTransparency = 255.000
closebtn.BorderSizePixel = 0
closebtn.Position = UDim2.new(0.946790934, 0, 0, 0)
closebtn.Size = UDim2.new(0, 23, 0, 23)
closebtn.Font = Enum.Font.SourceSans
closebtn.Text = ""
closebtn.TextColor3 = Color3.fromRGB(0, 0, 0)
closebtn.TextSize = 14.000
closebtn.MouseEnter:Connect(function()
	closelb.BackgroundColor3 = Color3.fromRGB(228, 238, 254)
end)
closebtn.MouseLeave:Connect(function()
	closelb.BackgroundColor3 = Color3.fromRGB(227, 227, 227)
end)
closebtn.MouseButton1Down:Connect(function()
	closelb.BackgroundColor3 = Color3.fromRGB(219, 219, 219)
end)

closebtn.MouseButton1Up:Connect(function()
	ratemyavatar:Destroy()
	script.Disabled = true
	script:Destroy()
end)


closelb.Name = "closelb"
closelb.Parent = closebtn
closelb.BackgroundColor3 = Color3.fromRGB(227, 227, 227)
closelb.BorderSizePixel = 0
closelb.Size = UDim2.new(0, 23, 0, 23)
closelb.Font = Enum.Font.SourceSans
closelb.Text = ""
closelb.TextColor3 = Color3.fromRGB(0, 0, 0)
closelb.TextSize = 14.000

closeimg.Name = "closeimg"
closeimg.Parent = closelb
closeimg.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
closeimg.BackgroundTransparency = 1.000
closeimg.BorderSizePixel = 0
closeimg.Position = UDim2.new(0.300999999, 0, 0.300999999, 0)
closeimg.Size = UDim2.new(0, 8, 0, 9)
closeimg.AutoButtonColor = false
closeimg.Image = "http://www.roblox.com/asset/?id=9345368867"
closeimg.ScaleType = Enum.ScaleType.Crop

title.Name = "title"
title.Parent = bar
title.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
title.BackgroundTransparency = 1.000
title.Position = UDim2.new(0.361363649, 0, 0.0434782617, 0)
title.Size = UDim2.new(0, 121, 0, 23)
title.Font = Enum.Font.SourceSans
title.Text = "Rate My Avatar - Menu"
title.TextColor3 = Color3.fromRGB(54, 54, 54)
title.TextSize = 14.000

